#ifndef API_STATUS_CODE_HPP
#define API_STATUS_CODE_HPP

enum class ApiStatusCode
{
    SUCCESS,
    CRITICAL_ABORT,

    INVALID_USER_INPUT,

    INVALID_REQUEST_BY_CLIENT,
    INVALID_REQUEST_BY_HOST,

    HOST_INITIALIZATION_ERROR,
    CLIENT_INITIALIZATION_ERROR,

    ILLEGAL_CLIENT_STATE,
    ILLEGAL_HOST_STATE,

    IO_ERROR,
    LOOKUP_ERROR,
    JSON_ERROR,
};

#endif // API_STATUS_CODE_HPP
